CREATE TABLE ##BlitzIndexFindings
([Priority] SMALLINT, [Finding] VARCHAR(500), [URL] NVARCHAR(500), [SanitizedFInding] VARCHAR(500), [Description] NVARCHAR(MAX))
GO
INSERT INTO
##BlitzIndexFindings ([Priority], [Finding], [URL], [Description])
VALUES
(20, 'Multiple Index Personalities: Duplicate keys', N'https://www.brentozar.com/go/duplicateindex',''),
(30, 'Multiple Index Personalities: Borderline duplicate keys', N'https://www.brentozar.com/go/duplicateindex',''),
(70, 'Aggressive Under-Indexing: Total lock wait time > 5 minutes (row + page)', N'https://www.brentozar.com/go/AggressiveIndexes',''),
(70, 'Aggressive Indexes: Total lock wait time > 5 minutes (row + page)', N'https://www.brentozar.com/go/AggressiveIndexes',''),
(70, 'Aggressive Over-Indexing: Total lock wait time > 5 minutes (row + page)', N'https://www.brentozar.com/go/AggressiveIndexes',''),
(10, 'Index Hoarder: Many NC Indexes on a Single Table', N'https://www.brentozar.com/go/IndexHoarder',''),
(10, 'Index Hoarder: Unused NC Index with High Writes', N'https://www.brentozar.com/go/IndexHoarder',''),
(80, 'Abnormal Psychology: Filter Columns Not In Index Definition', N'https://www.brentozar.com/go/IndexFeatures',''),
(100, 'Self Loathing Indexes: Low Fill Factor on Nonclustered Index', N'https://www.brentozar.com/go/SelfLoathing',''),
(100, 'Self Loathing Indexes: Low Fill Factor on Clustered Index', N'https://www.brentozar.com/go/SelfLoathing',''),
(100, 'Self Loathing Indexes: Heaps with Forwarded Fetches', N'https://www.brentozar.com/go/SelfLoathing',''),
(100, 'Self Loathing Indexes: Large Active Heap', N'https://www.brentozar.com/go/SelfLoathing',''),
(100, 'Self Loathing Indexes: Medium Active heap',N'https://www.brentozar.com/go/SelfLoathing',''),
(100, 'Self Loathing Indexes: Small Active heap',N'https://www.brentozar.com/go/SelfLoathing',''),
(100, 'Self Loathing Indexes: Heap with a Nonclustered Primary Key',N'https://www.brentozar.com/go/SelfLoathing',''),
(100, 'Index Hoarder: NC index with High Writes:Reads',N'https://www.brentozar.com/go/IndexHoarder',''),
(40, 'Indexaphobia: High Value Missing Index',N'https://www.brentozar.com/go/Indexaphobia',''),
(80,'Abnormal Psychology: Identity Column Within xx Percent End of Range',N'https://www.brentozar.com/go/AbnormalPsychology',''),
(80, 'Abnormal Psychology: Columnstore Indexes with Trace Flag 834', N'https://support.microsoft.com/en-us/kb/3210239',''),
(90,'Functioning Statistaholics: Statistics Not Updated Recently','https://www.brentozar.com/go/stats',''),
(90, 'Functioning Statistaholics: Low Sampling Rates','https://www.brentozar.com/go/stats',''),
(90, 'Functioning Statistaholics: Statistics With NO RECOMPUTE','https://www.brentozar.com/go/stats',''),
(100, 'Serial Forcer: Check Constraint with Scalar UDF', 'https://www.brentozar.com/go/computedscalar',''),
(100, 'Serial Forcer: Computed Column with Scalar UDF', 'https://www.brentozar.com/go/computedscalar',''),
(150,'Index Hoarder: More Than 5 Percent NC Indexes Are Unused',N'https://www.brentozar.com/go/IndexHoarder',''),
(150, 'Index Hoarder: Borderline: Wide Indexes (7 or More Columns)',N'https://www.brentozar.com/go/IndexHoarder',''),
(150, 'Index Hoarder: Wide Clustered Index (> 3 columns OR > 16 bytes)',N'https://www.brentozar.com/go/IndexHoarder',''),
(200, 'Index Hoarder: Addicted to Nulls',N'https://www.brentozar.com/go/IndexHoarder',''),
(150, 'Index Hoarder: Wide Tables: 35+ cols or > 2000 non-LOB bytes',N'https://www.brentozar.com/go/IndexHoarder',''),
(200, 'Index Hoarder: Addicted to strings',N'https://www.brentozar.com/go/IndexHoarder',''),
(150, 'Index Hoarder: Non-Unique Clustered Index',N'https://www.brentozar.com/go/IndexHoarder',''),
(150, 'Index Hoarder: Unused NC index with Low Writes',N'https://www.brentozar.com/go/IndexHoarder',''),
(250,'Feature-Phobic Indexes: No Indexes Use Includes','https://www.brentozar.com/go/IndexFeatures',''),
(250,'Feature-Phobic Indexes: Few Indexes Use Includes','https://www.brentozar.com/go/IndexFeatures',''),
(250,'Feature-Phobic Indexes: No Filtered Indexes or Indexed Views','https://www.brentozar.com/go/IndexFeatures',''),
(250,'Feature-Phobic Indexes: Potential Filtered Index (Based on Column Name)','https://www.brentozar.com/go/IndexFeatures',''),
(150, 'Self Loathing Indexes: Hypothetical Index', N'https://www.brentozar.com/go/SelfLoathing',''),
(150, 'Self Loathing Indexes: Disabled Index', N'https://www.brentozar.com/go/SelfLoathing',''),
(200, 'Self Loathing Indexes: Heaps with Deletes', N'https://www.brentozar.com/go/SelfLoathing',''),
(150, 'Abnormal Psychology: XML Index', N'https://www.brentozar.com/go/AbnormalPsychology',''),
(150, 'Abnormal Psychology: NC Columnstore Index', N'https://www.brentozar.com/go/AbnormalPsychology',''),
(150, 'Abnormal Psychology: Clustered Columnstore Index', N'https://www.brentozar.com/go/AbnormalPsychology',''),
(150, 'Abnormal Psychology: Spatial Index', N'https://www.brentozar.com/go/AbnormalPsychology',''),
(150, 'Abnormal Psychology: Compressed Index', N'https://www.brentozar.com/go/AbnormalPsychology',''),
(150, 'Abnormal Psychology: Partitioned Index', N'https://www.brentozar.com/go/AbnormalPsychology',''),
(150, 'Abnormal Psychology: Non-Aligned Index on a Partitioned Table', N'https://www.brentozar.com/go/AbnormalPsychology',''),
(200, 'Abnormal Psychology: Recently Created Tables/Indexes (1 week)', N'https://www.brentozar.com/go/AbnormalPsychology',''),
(200, 'Abnormal Psychology: Recently Modified Tables/Indexes (2 days)', N'https://www.brentozar.com/go/AbnormalPsychology',''),
(150, 'Abnormal Psychology: Column Collation Does Not Match Database Collation', N'https://www.brentozar.com/go/AbnormalPsychology',''),
(200, 'Abnormal Psychology: Replicated Columns', N'https://www.brentozar.com/go/AbnormalPsychology',''),
(150, 'Abnormal Psychology: Cascading Updates or Deletes', N'https://www.brentozar.com/go/AbnormalPsychology',''),
(150, 'Abnormal Psychology: Unindexed Foreign Keys', N'https://www.brentozar.com/go/AbnormalPsychology',''),
(150, 'Abnormal Psychology: In-Memory OLTP', N'https://www.brentozar.com/go/AbnormalPsychology',''),
(200, 'Abnormal Psychology: Identity Column Using a Negative Seed or Increment Other Than 1', N'https://www.brentozar.com/go/AbnormalPsychology',''),
(200, 'Workaholics: Scan-a-lots (index-usage-stats)',N'https://www.brentozar.com/go/Workaholics',''),
(200, 'Workaholics: Top Recent Accesses (index-op-stats)',N'https://www.brentozar.com/go/Workaholics',''),
(200, 'Functioning Statistaholics: Filter Fixation',N'https://www.brentozar.com/go/stats',''),
(200, 'Cold Calculators: Definition Defeatists',N'',''),
(200, 'Abnormal Psychology: Temporal Tables',N'',''),
(200, 'Medicated Indexes: Optimized For Sequential Keys',N'','')
